[2023-08-17T15:21:45.661-0600] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Respaldar_Documentos_Electronicos.sincronizar_archivos manual__2023-08-17T21:21:43.371069+00:00 [queued]>
[2023-08-17T15:21:45.675-0600] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Respaldar_Documentos_Electronicos.sincronizar_archivos manual__2023-08-17T21:21:43.371069+00:00 [queued]>
[2023-08-17T15:21:45.676-0600] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-08-17T15:21:45.706-0600] {taskinstance.py:1327} INFO - Executing <Task(SSHOperator): sincronizar_archivos> on 2023-08-17 21:21:43.371069+00:00
[2023-08-17T15:21:45.712-0600] {standard_task_runner.py:57} INFO - Started process 2883 to run task
[2023-08-17T15:21:45.716-0600] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Respaldar_Documentos_Electronicos', 'sincronizar_archivos', 'manual__2023-08-17T21:21:43.371069+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/respaldar_documentos_electronicos.py', '--cfg-path', '/tmp/tmpkmrou8_z']
[2023-08-17T15:21:45.719-0600] {standard_task_runner.py:85} INFO - Job 17: Subtask sincronizar_archivos
[2023-08-17T15:21:45.779-0600] {task_command.py:410} INFO - Running <TaskInstance: Respaldar_Documentos_Electronicos.sincronizar_archivos manual__2023-08-17T21:21:43.371069+00:00 [running]> on host f001d94713ae
[2023-08-17T15:21:45.946-0600] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Respaldar_Documentos_Electronicos' AIRFLOW_CTX_TASK_ID='sincronizar_archivos' AIRFLOW_CTX_EXECUTION_DATE='2023-08-17T21:21:43.371069+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-17T21:21:43.371069+00:00'
[2023-08-17T15:21:45.946-0600] {ssh.py:135} INFO - Creating ssh_client
[2023-08-17T15:21:46.001-0600] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-08-17T15:21:46.014-0600] {base.py:73} INFO - Using connection ID 'gabo_ssh' for task execution.
[2023-08-17T15:21:46.015-0600] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-08-17T15:21:46.036-0600] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_9.2p1)
[2023-08-17T15:21:46.184-0600] {transport.py:1873} INFO - Authentication (password) successful!
[2023-08-17T15:21:46.185-0600] {ssh.py:476} INFO - Running command: rsync -a /var/www/gabos/application/third_party/ ~/Dropbox/Inversiones_Garotas_Bonitas/GABO/respaldos/documentos_electronicos
[2023-08-17T15:21:46.396-0600] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Respaldar_Documentos_Electronicos, task_id=sincronizar_archivos, execution_date=20230817T212143, start_date=20230817T212145, end_date=20230817T212146
[2023-08-17T15:21:46.450-0600] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-17T15:21:46.482-0600] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
